### PR TITLE
Gh enterprise 1878

### PR DESCRIPTION
**Pull request by danantonioreyes**

### CODE REVIEW

**Comment by bendk** [comment]
Code looks good to me, my one concern is the performance of it, since you're iterating through all approval assignments.  For many teams this should be fairly short, but for TED it might be very large.

I don't think we should try optimizing too much at this point, but one simple change would be to skip that code if the user is an actual manager, since then you know that can_approve_collaboration() will always return true.

**Comment by danantonioreyes** [comment]
Added check for just projer and language manager

**Comment by bendk** [comment]
Looks great to me, except there's a merge conflict.  Can you merge dev/master to your branches?

**Comment by danantonioreyes** [comment]
Forgot to push my dev/master merge. Should be ok now

**Pull request merged**
