### PR TITLE
Fix #3129.

### LINKED ISSUE #3129: AttributeError: 'BaseNotification' object has no attribute 'version'
https://sentry.io/pculture/unisubs-staging/issues/471661215/

```
AttributeError: 'BaseNotification' object has no attribute 'version'
(2 additional frame(s) were not displayed)
...
  File "teams/tasks.py", line 154, in api_notify_on_language_activity
    team_pk, event_name, language_pk=language_pk, video_id=language.video.video_id)
  File "teams/models.py", line 3240, in notify_team
    notification_settings.notify(event_name, **kwargs)
  File "teams/models.py", line 3317, in notify
    event_name,  **kwargs)
  File "teams/notifications.py", line 107, in __init__
    self.api_url = self.get_api_url()
  File "teams/notifications.py", line 122, in get_api_url
    if self.version:

AttributeError: 'BaseNotification' object has no attribute 'version'
```

### PR DESCRIPTION
**Pull request by metanerd**

### CODE REVIEW

**Comment by bendk** [comment]
I don't think this will fix the issue.  django should automatically setup the version attribute.  If version_pk is None, version should automatically be None as well.

Were you able to reproduce the issue and test that this change fixes it?

**Comment by metanerd** [comment]
No, I didn't test this locally. It is a shot in the dark. I tried reproducing it with creating teams and team notifications. There seem to be a lot of edge cases which I do not know of.

**Comment by bendk** [comment]
Understandable.  Thanks for trying though! If you want to help out I could probably find a more suitable issue.

**Comment by metanerd** [comment]
I would be up for a more suitable issue.

**Comment by bendk** [comment]
@metanerd How about this one? https://github.com/pculture/unisubs/issues/3371

**Comment by metanerd** [comment]
Yes, I started with it. I got stuck at finding out what CTA context means and how it works. What does the acronym stand for?
https://github.com/metanerd/unisubs/compare/dev...metanerd:add-team-slug

**Pull request closed without merging**
