### PR TITLE
Hide subnav link

### PR DESCRIPTION
**Pull request by deanjansen**
Temporarily hid subnav link, awaiting new teams UI

### CODE REVIEW

**Comment by bendk** [comment]
The code seems fine to me.  Has someone tested it?

**Comment by deanjansen** [comment]
My local instance is stuck, so I had trouble verifying it.

**Comment by deanjansen** [comment]
I gave it a quick test and it seems to be working as expected.

**Comment by PCF-Testing** [comment]
Tested locally, have not found any issues with the branch.

**Pull request merged**
