### PR TITLE
Updating submodule AE. Removed Stevie Varin's bio

### PR DESCRIPTION
**Pull request by danantonioreyes**

### CODE REVIEW

**Comment by danantonioreyes** [comment]
Personal note: double check where `.grid` is used and see if it's okay to change it from `justify-content: space-between` to `justify-content: center`

**Comment by danantonioreyes** [comment]
Changed `.grid justify-content` from `space-between` to `center`

**Comment by bendk** [comment]
The amara-assets change seems good, but now the amara-enterprise changes seem empty.  Can you take a look at that?

**Comment by danantonioreyes** [comment]
Could you check again? I just pushed some commits in the `amara-enterprise/gh-enterprise-1999` branch

**Pull request merged**
