### PR TITLE
Gh enterprise 1877

### PR DESCRIPTION
**Pull request by danantonioreyes**
This pull request covers three issues:

https://github.com/pculture/amara-enterprise/issues/1877
https://github.com/pculture/amara-enterprise/issues/1879
https://github.com/pculture/amara-enterprise/issues/1939

Things got really messy while writing code for these three issues and I just decided to put them all in one branch

### CODE REVIEW

**Comment by bendk** [comment]
Just saw the amara-enterprise PR.  Going to add comments there.

**Comment by danantonioreyes** [comment]
Implemented quite a handful of changes to the code for this

**Comment by bendk** [comment]
The changes here and in amara-entperprise look good to me.  Feel free to merge whenever is good for you @danantonioreyes .

**Comment by danantonioreyes** [comment]
Merged

**Pull request merged**
