### PR TITLE
Toogle Tool Icon Without Ugly Focus Ring

### PR DESCRIPTION
**Pull request by jessehall3**
Addresses Issue #1740

#1740

The tool icon is now a button that can toggle the toolbox menu in and out of view.

NEW in this pull request:  No more ugly focus ring!

Details:
"outline: none;" killed the problematic focus ring.

I played around with some custom focus rings in css, but they ultimately seemed more confusing than helpful. I say that because tabbing will not move the focus (along with the focus ring) as is the expected behavior for most web pages. Instead tabbing is tied directly to controlling the video player. Because clicking the icon will toggle its color, I think it'd be better to eliminate the focus ring all together.

### CODE REVIEW

**Comment by PCF-Testing** [comment]
Looks fine now.

**Comment by bendk** [comment]
I tihnk we're going to go with this solution.

**Comment by jessehall3** [comment]
Did you notice the more recent pull request here: https://github.com/pculture/unisubs/pull/2608 ?

First, it closes the toolbox menu if you click anywhere outside of it.
Second, it's more recent and currently has no merge conflicts.

**Comment by bendk** [comment]
Yes we saw that one.  I think the confusion comes from the name of the PR.  "helper margin" seems like a focus ring, but we wanted to skip that part for now.  Maybe we're reading that wrong and it's just whitespace though.

**Comment by jessehall3** [comment]
The latest PR has all the features we've been discussing.

The "helper margin" is not the focus ring, it's the invisible margin to the left of the tool box. This feature was in a previous PR and is currently merged.

The latest PR is the only one that will close the toolbox after clicking outside the toolbox menu -- this is the feature we discussed a couple of weeks ago.

The latest PR has no focus ring. It has uses 'teal' for the button color. Those things have not changed.

Sorry for the confusing titles.

**Comment by PCF-Testing** [comment]
Planning to merge 2608 instead of this one.

**Pull request closed without merging**
